<?php
  ini_set('display_errors',1);
  error_reporting(E_ALL);
  define("PROJECT_ROOT","/var/www/html/hostel/");
  define("DS","/");
  define("BASE_URL","http://localhost/hostel/public/");
  define("DB_USER","root");
  define("DB_NAME","hostel");
  define("DB_SERVER","127.0.0.1");
  define("DB_PASSWD","3r89f");
?>
